"use client";
import React from "react";
import { motion } from "framer-motion";
import { CheckCircle2, ArrowRight, UserCheck, ShieldCheck, Store, ShoppingBag } from "lucide-react";

const connectedSteps = [
  {
    step: "01",
    title: "Buyer Explores Marketplace",
    desc: "Discovers verified vehicles with complete specifications, diagnostic photos, and seller ratings.",
    icon: ShoppingBag,
    accent: "border-fourth/30 text-fourth bg-fourth/10"
  },
  {
    step: "02",
    title: "Verified Consultant Storefront",
    desc: "Direct communication with established automotive consultants with real digital credibility.",
    icon: Store,
    accent: "border-indigo-500/30 text-indigo-400 bg-indigo-500/10"
  },
  {
    step: "03",
    title: "Standardized Inspection Audit",
    desc: "Full multi-point technical inspection report generated by professional automotive inspectors.",
    icon: ShieldCheck,
    accent: "border-emerald-500/30 text-emerald-400 bg-emerald-500/10"
  },
  {
    step: "04",
    title: "Confident & Safe Transaction",
    desc: "Buyer and consultant conclude transaction with full transparency and verified records.",
    icon: UserCheck,
    accent: "border-purple-500/30 text-purple-400 bg-purple-500/10"
  }
];

export default function ConnectedEcosystem() {
  return (
    <section id="ecosystem" className="py-24 bg-transparent text-primary border-b border-white/10 relative">
      <div className="max-w-[1440px] mx-auto px-6 md:px-[80px]">
        
        {/* Header */}
        <div className="text-center max-w-[840px] mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-fourth/10 border border-fourth/30 text-fourth text-xs font-mono font-bold uppercase mb-4">
            <CheckCircle2 className="w-4 h-4" />
            The Unified Solution
          </div>
          <h2 className="text-3xl sm:text-5xl font-bold tracking-tight mb-4 font-[Montserrat] text-primary">
            Meet Reecomm: Everything Connected
          </h2>
          <p className="text-lg text-third">
            Reecomm isn&apos;t just another listing site — it is the trust infrastructure that connects buyers, sellers, consultants, and inspectors into one transparent ecosystem.
          </p>
        </div>

        {/* Connected Flow Diagram */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
          {connectedSteps.map((item, idx) => {
            const Icon = item.icon;
            return (
              <div
                key={idx}
                className="relative rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-6">
                    <span className="text-xs font-mono font-bold text-third uppercase tracking-widest">
                      Step {item.step}
                    </span>
                    <div className={`p-3 rounded-xl border ${item.accent}`}>
                      <Icon className="w-5 h-5" />
                    </div>
                  </div>

                  <h3 className="text-xl font-bold text-primary mb-3">
                    {item.title}
                  </h3>

                  <p className="text-sm text-third leading-relaxed">
                    {item.desc}
                  </p>
                </div>

                {idx < connectedSteps.length - 1 && (
                  <div className="hidden lg:block absolute -right-3 top-1/2 -translate-y-1/2 z-20">
                    <div className="w-6 h-6 rounded-full bg-black/60 border border-white/10 flex items-center justify-center text-third">
                      <ArrowRight className="w-3.5 h-3.5" />
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
