/**
 * /vehicle/details/[id]
 *
 * Catch-all redirect for UUID-only vehicle share links generated by the mobile app.
 *
 * Problem:
 *   The mobile app shares links in the form:
 *     https://www.reecomm.com/vehicle/details/{uuid}
 *   But the canonical web page lives at:
 *     https://www.reecomm.com/vehicle/details/{slug}/{uuid}
 *   → UUID-only paths hit a 404.
 *
 * Solution:
 *   This page uses getServerSideProps to:
 *   1. Fetch the vehicle from the backend API by UUID.
 *   2. Build the slug from the vehicle data (mirrors generateVehicleSlug in helper.js).
 *   3. 301-redirect to the canonical /vehicle/details/{slug}/{uuid} URL.
 *
 * If the vehicle is not found, return a 404.
 */

// This component is never rendered — getServerSideProps always redirects or returns notFound.
export default function VehicleRedirect() {
  return null;
}

// ─── Slug builder (mirrors generateVehicleSlug from @/lib/helper.js) ─────────

function buildVehicleSlug(v) {
  const brandPart = (v.makerName || "").toLowerCase().replace(/\s+/g, "-");
  const modelPart = (v.modelName || "").toLowerCase().replace(/\s+/g, "-");
  const yearPart = v.yearOfMfg || v.year || "";
  const cityPart = (
    v.vehicleAddress?.city ||
    v.cityName ||
    v.city ||
    v.address?.city ||
    v.location ||
    ""
  )
    .split(",")[0]
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-");

  const vehicleKind =
    (v.vehicleType || "").toUpperCase().includes("TWO")
      ? "two-wheelers"
      : "cars";

  return `buy-used-${brandPart}-${modelPart}-${yearPart}-${vehicleKind}-${cityPart}`
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// ─── Server-Side Redirect ────────────────────────────────────────────────────

export async function getServerSideProps(context) {
  const { id } = context.params || {};

  if (!id) {
    return { notFound: true };
  }

  // Guard: if `id` looks like a slug (contains letters + dashes without UUID format),
  // it means the [title] segment was skipped — skip silently.
  const UUID_REGEX =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!UUID_REGEX.test(id)) {
    return { notFound: true };
  }

  try {
    const backendUrl =
      process.env.BACKEND_URL || "https://api.reecomm.online";

    const res = await fetch(
      `${backendUrl}/api/v1/website/vehicle/detail-page/${id}`,
      {
        headers: { Accept: "application/json" },
        signal: AbortSignal.timeout(5000),
      }
    );

    if (!res.ok) {
      return { notFound: true };
    }

    const json = await res.json();
    const vehicle = json?.data;

    if (!vehicle || !vehicle.id) {
      return { notFound: true };
    }

    const slug = buildVehicleSlug(vehicle) || "vehicle";

    // 301 = permanent redirect — crawlers will update their link index
    return {
      redirect: {
        destination: `/vehicle/details/${slug}/${id}`,
        permanent: true,
      },
    };
  } catch {
    // Network / timeout — don't 404 hard, let the user try again
    return { notFound: true };
  }
}
